apiVersion: v1
kind: Service
metadata:
  name: jenkins-cd-demo-lb
spec:
  selector:
    app: jenkins-cd-demo
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-cd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-cd-demo
  template:
    metadata:
      labels:
        app: jenkins-cd-demo
    spec:
      containers:
        - name: jenkins-cd-demo
#          image: "${ECR_REGISTRY_URI}:${IMAGE_TAG}"
          image: 153657280434.dkr.ecr.eu-west-1.amazonaws.com/demo:latest
      imagePullSecrets:
        - name: aws-ecr